In [11]:
#This is run in (base)env , can import numpy (means anaconda works!)
# randint(start, end)
from random import randint
a = randint(0,2) #2 is included!!
print(a) #2
numlist = []
templist = []
def randint_add(num):
    for x in range(num):
        numlist.append(x)
        templist.append(randint(0,2))
    return numlist, templist
result = randint_add(10)    
print(f"numlist : {result[0]} \ntemplist: {result[1]}")



2
numlist : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 
templist: [0, 1, 2, 1, 0, 1, 2, 2, 1, 2]


### numpy.random.randint(low, high=None, size=None, dtype='l')¶

In [17]:
print("------np.random.randint------")
import numpy as np
print(np.random.randint(2))
print(np.random.randint(2))
print(np.random.randint(2))

print(np.random.randint(2, size=10)) #[0 0 1 1 0 1 0 1 0 0] #2 is not incl


------np.random.randint------
1
1
0
[1 0 0 0 0 1 1 0 0 1]


In [12]:
np.random.randint(5, size=(2, 4)) #from 0 to 4, 5 is not incl
# array([[2, 0, 2, 3],
#        [1, 3, 4, 4]])

array([[2, 0, 2, 3],
       [1, 3, 4, 4]])

In [15]:
np.random.randint(1,9, size=(4, 6)) #start from 1 to 9 random integer 
# array([[4, 8, 2, 2, 3, 4],
#        [4, 6, 8, 5, 3, 7],
#        [1, 4, 2, 7, 6, 5],
#        [7, 1, 2, 1, 4, 4]])

array([[4, 8, 2, 2, 3, 4],
       [4, 6, 8, 5, 3, 7],
       [1, 4, 2, 7, 6, 5],
       [7, 1, 2, 1, 4, 4]])